version: "3"

services:
    node:
      container_name: marie.node
      build:
        context: ./
        dockerfile: Dockerfile.dev
      volumes:
        - ./site:/home/node/app
      command: npm start

    nginx:
      container_name: marie.nginx
      image: nginx
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./.provision/ssl:/etc/ssl
        - ./.provision/software/nginx/conf.d:/etc/nginx/conf.d:ro
        - ./build:/usr/share/nginx/html
      links:
        - node
