name: Makefile CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make install-dependencies

      - name: Build
        run: make build

      - name: Committing build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "Generated build"
          git push
